version: '3'

services:
    php:
        image: php:8.0.13
        working_dir: /app
        volumes:
            - type: bind
              source: ./
              target: /app
        command:
            -  tail
            - -f
            - /dev/null
